name: publish-packages
on:
  push:
    branches:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 12
        registry-url: https://npm.pkg.github.com/
        scope: '@dtothefp'
    - name: Publish to GitHub Package Registry
      run: |
        cd packages/core
        yarn publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
