name: publish-packages
on:
  # workflow_dispatch:
    # inputs:
      # name:
        # description: 'Person to greet'
        # required: true
        # default: 'Mona the Octocat'
      # home:
        # description: 'location'
        # required: false
      # message:
        # description: 'the commit message'
        # required: true
        # default: 'The default message'
  push:
    branches: [master,devel]
  pull_request:
    branches: '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtothefp/actions-ci-env@master
    - uses: dtothefp/setup-node@dfp-auth
      with:
        node-version: 12
        registry-url: https://npm.pkg.github.com/
      env:
        ACTIONS_STEP_DEBUG: ${{secrets.ACTIONS_STEP_DEBUG}}
    - uses: webfactory/ssh-agent@v0.2.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Install
      run: yarn
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        NPM_TOKEN_GRX: ${{secrets.NPM_TOKEN_GRX}}
        ACTIONS_STEP_DEBUG: ${{secrets.ACTIONS_STEP_DEBUG}}
    - name: Publish to GitHub Package Registry
      run: |
            if [ "$BRANCH_NAME" = "master" ]; then
              git checkout master
              git config --global user.name "dtothefp"
              git config --global user.email "dtothefp@gmail.com"
              git remote set-url origin "git@github.com:dtothefp/github-packages-publish.git"
              git remote show origin
              git config user.name
              git config user.email
              yarn lerna publish patch \
              --registry "https://npm.pkg.github.com/" \
              --yes \
              --no-verify-access \
              --exact \
              --force-publish
            else
              # yarn lerna publish \
              # --registry "https://npm.pkg.github.com/" \
              # --yes \
              # --no-verify-access \
              # --canary \
              # --no-push \
              # --exact \
              # --force-publish \
              # --preid "${BRANCH_NAME}-${GITHUB_SHA:0:7}"
              echo "skip publish"
            fi
      env:
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        NPM_TOKEN_GRX: ${{secrets.NPM_TOKEN_GRX}}
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
