name: test-triggers
on:
  push:
    branches: [master]
  pull_request:
    branches: '*'
jobs:
  test-trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtothefp/setup-node@dfp-auth
      with:
        node-version: 12
        registry-url: https://npm.pkg.github.com/
      env:
        ACTIONS_STEP_DEBUG: ${{secrets.ACTIONS_STEP_DEBUG}}
    - name: Echo Env
      run: |
        echo "REF_BRANCH $REF_BRANCH"
        echo "EVENT_BRANCH $EVENT_BRANCH"
      env:
        REF_BRANCH: ${{ env.GITHUB_REF }}
        EVENT_BRANCH: {{ github.event.pull_request.head.ref }}
    - name: Install
      run: yarn
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        NPM_TOKEN_GRX: ${{secrets.NPM_TOKEN_GRX}}
        ACTIONS_STEP_DEBUG: ${{secrets.ACTIONS_STEP_DEBUG}}
    - name: Echo to STDOUT
      run: |
        echo "Running Changed Stuff"
